// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package languageselector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the LanguageSelector module
	public static void aCT__LoadLanguageItems(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("LanguageSelector.ACT__LoadLanguageItems").withParams(params).execute(context);
	}
	public static languageselector.proxies.LanguageSelector dS__LanguageSelector(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("LanguageSelector.DS__LanguageSelector").withParams(params).execute(context);
		return result == null ? null : languageselector.proxies.LanguageSelector.initialize(context, result);
	}
	public static languageselector.proxies.LanguageItem sUB__GetLanguageItem_by_SysLanguage(IContext context, system.proxies.Language _systemLanguage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SystemLanguage", _systemLanguage == null ? null : _systemLanguage.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("LanguageSelector.SUB__GetLanguageItem_by_SysLanguage").withParams(params).execute(context);
		return result == null ? null : languageselector.proxies.LanguageItem.initialize(context, result);
	}
	public static void sUB__LoadLanguageItems(IContext context, boolean _retainLast2Chars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RetainLast2Chars", _retainLast2Chars);
		Core.microflowCall("LanguageSelector.SUB__LoadLanguageItems").withParams(params).execute(context);
	}
	public static boolean sUB__SwitchLanguage(IContext context, system.proxies.Language _newSystemLanguage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewSystemLanguage", _newSystemLanguage == null ? null : _newSystemLanguage.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("LanguageSelector.SUB__SwitchLanguage").withParams(params).execute(context);
	}
}
