// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package languageselector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the LanguageSelector module
	public static void aCT__LoadLanguageItems(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("LanguageSelector.ACT__LoadLanguageItems").withParams(params).execute(context);
	}
	public static languageselector.proxies.LanguageSelector dS__LanguageSelector(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("LanguageSelector.DS__LanguageSelector").withParams(params).execute(context);
		return result == null ? null : languageselector.proxies.LanguageSelector.initialize(context, result);
	}
	public static languageselector.proxies.LanguageItem sUB__GetLanguageItem_by_SysLanguage(IContext context, system.proxies.Language _sysLanguage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SysLanguage", _sysLanguage == null ? null : _sysLanguage.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("LanguageSelector.SUB__GetLanguageItem_by_SysLanguage").withParams(params).execute(context);
		return result == null ? null : languageselector.proxies.LanguageItem.initialize(context, result);
	}
	public static boolean sUB__SwitchLanguage(IContext context, system.proxies.Language _newSystemLanguage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NewSystemLanguage", _newSystemLanguage == null ? null : _newSystemLanguage.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("LanguageSelector.SUB__SwitchLanguage").withParams(params).execute(context);
	}
}